### ISSUE TITLE
[Question] 404 - Not Found when using jekyll-remote-theme 

### ISSUE THREAD

**Issue by nikhilaravi** [daviddarnes/alembic#165]
I downloaded the  "GitHub Pages with Remote starter kit" and tried to run it after doing `bundle install` but I am getting the error that the theme is not found to download:

```
Incremental build: disabled. Enable with --incremental
      Generating... 
      Remote Theme: Using theme daviddarnes/alembic
jekyll 3.9.0 | Error:  404 - Not Found
/Users/Nikhila/.rvm/gems/ruby-3.0.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/downloader.rb:67:in `raise_unless_sucess': 404 - Not Found (Jekyll::RemoteTheme::DownloadError)
	from /Users/Nikhila/.rvm/gems/ruby-3.0.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/downloader.rb:44:in `block (2 levels) in download'
	from /Users/Nikhila/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/net/http.rb:1566:in `block in transport_request'
	from /Users/Nikhila/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/net/http/response.rb:167:in `reading_body'
	from /Users/Nikhila/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/net/http.rb:1565:in `transport_request'
	from /Users/Nikhila/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/net/http.rb:1521:in `request'
```

**Comment by daviddarnes** [comment]
Thanks for reporting this @nikhilaravi! Looks like I hadn't updated the kits with the most recent updates. Also I renamed the branch from `master` to `main` which caused this issue to appear https://github.com/benbalter/jekyll-remote-theme/issues/84

Thankfully it wasn't too much trouble to amend. Try downloading it again and see how you get on. Report back here if you have any further problems 😄
