### ISSUE TITLE
Remote theme failing with 404

### ISSUE THREAD

**Issue by j-harg** [daviddarnes/alembic#167]
**[Question]**

Morning.  Been using Alembic as a remote theme on GH pages successfully until a few weeks ago - adding more content this morning and it fails to build locally (and GH pages).

Building locally with `bundle exec jekyll serve ` gives
                                                        
```
Configuration file: /Users/jah/projects/j-harg.github.io/_config.yml
            Source: /Users/jah/projects/j-harg.github.io
       Destination: /Users/jah/projects/j-harg.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme daviddarnes/alembic
jekyll 3.9.0 | Error:  404 - Not Found
Traceback (most recent call last):
	48: from /Users/jah/.gem/ruby/2.7.0/bin/bundle:23:in `<main>'
	47: from /Users/jah/.gem/ruby/2.7.0/bin/bundle:23:in `load'
	46: from /Users/jah/.gem/ruby/2.7.0/gems/bundler-2.2.1/exe/bundle:37:in `<top (required)>'
	45: from /Users/jah/.gem/ruby/2.7.0/gems/bundler-2.2.1/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	44: from /Users/jah/.gem/ruby/2.7.0/gems/bundler-2.2.1/exe/bundle:49:in `block in <top (required)>'
	43: from /Users/jah/.gem/ruby/2.7.0/gems/bundler-2.2.1/lib/bundler/cli.rb:24:in `start'
	42: from /Users/jah/.gem/ruby/2.7.0/gems/bundler-2.2.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	41: from /Users/jah/.gem/ruby/2.7.0/gems/bundler-2.2.1/lib/bundler/cli.rb:30:in `dispatch'
	40: from /Users/jah/.gem/ruby/2.7.0/gems/bundler-2.2.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	39: from /Users/jah/.gem/ruby/2.7.0/gems/bundler-2.2.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	38: from /Users/jah/.gem/ruby/2.7.0/gems/bundler-2.2.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	37: from /Users/jah/.gem/ruby/2.7.0/gems/bundler-2.2.1/lib/bundler/cli.rb:497:in `exec'
	36: from /Users/jah/.gem/ruby/2.7.0/gems/bundler-2.2.1/lib/bundler/cli/exec.rb:28:in `run'
	35: from /Users/jah/.gem/ruby/2.7.0/gems/bundler-2.2.1/lib/bundler/cli/exec.rb:63:in `kernel_load'
	34: from /Users/jah/.gem/ruby/2.7.0/gems/bundler-2.2.1/lib/bundler/cli/exec.rb:63:in `load'
	33: from /usr/local/lib/ruby/gems/2.7.0/bin/jekyll:23:in `<top (required)>'
	32: from /usr/local/lib/ruby/gems/2.7.0/bin/jekyll:23:in `load'
	31: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
	30: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	29: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	28: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	27: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	26: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	25: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	24: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'
	23: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'
	22: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
	21: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:36:in `process'
	20: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:65:in `build'
	19: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/command.rb:28:in `process_site'
	18: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/site.rb:68:in `process'
	17: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/site.rb:105:in `reset'
	16: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/hooks.rb:102:in `trigger'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/hooks.rb:102:in `each'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/hooks.rb:103:in `block in trigger'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme.rb:33:in `block in <top (required)>'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme.rb:27:in `init'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/munger.rb:25:in `munge!'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/downloader.rb:24:in `run'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/downloader.rb:42:in `download'
	 8: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/http.rb:606:in `start'
	 7: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/http.rb:933:in `start'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/downloader.rb:43:in `block in download'
	 5: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/http.rb:1492:in `request'
	 4: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/http.rb:1536:in `transport_request'
	 3: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/http/response.rb:167:in `reading_body'
	 2: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/http.rb:1537:in `block in transport_request'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/downloader.rb:44:in `block (2 levels) in download'
/usr/local/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/downloader.rb:67:in `raise_unless_sucess': 404 - Not Found (Jekyll::RemoteTheme::DownloadError)
```
No known changes on my side - so many apologies if being very dim.  Noticed that there was a recent version bump to 4.1.0 a couple of weeks ago and wondering if that is related, but looking at the changes it doesn't seem likely.  Any pointers would be much appreciated.

**Comment by daviddarnes** [comment]
Hey @j-harg, this was fixed in https://github.com/daviddarnes/alembic/issues/165. I changed the main repo from `master` to `main`, which caused the bug shown in https://github.com/benbalter/jekyll-remote-theme/issues/84 to show up. Quickest fix is to add `@main` to the end of the value on the `remote_theme` key in your config. You can also refer to the kit I recently updated here https://github.com/daviddarnes/alembic-kit

Hope this helps!

**Comment by j-harg** [comment]
Awesome - thanks!  Soz, should have looked that the older issues.  Thanks again
