### ISSUE TITLE
[Bug]: Alembic Theme Not Found Download Error in GitHub Pages

### ISSUE THREAD

**Issue by olivia1117** [daviddarnes/alembic#169]
## Summary
In recent versions of GitHub pages, Alembic is not found as a remote theme and the website doesn't load or compile. It last compiled successfully on November 21st, 2020. When I tried to commit on February 7th, 2021, it didn't work. When I rolled back my commits, it still didn't work either. Here's a link to my commit history: https://github.com/olivia1117/LakeWaterLevelData/commits/gh-pages 

## To Reproduce
Steps to reproduce the behaviour:
1) Clone the GitHub repo
- git clone https://github.com/olivia1117/LakeWaterLevelData.git
- git checkout -b gh-pages
2) Set up the environment
- https://docs.github.com/en/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll

## Expected behaviour
The website should compile and run using `bundle exec jekyll serve`

## Error message
 ```
Incremental build: disabled. Enable with --incremental                                                                       

Generating...                                                                                                           
Remote Theme: Using theme daviddarnes/alembic                                                                     
jekyll 3.9.0 | Error:  404 - Not Found                                                                                  
Traceback (most recent call last):                                                                                              

33: from C:/Ruby27-x64/bin/jekyll:23:in `<main>`   
                                                                  
32: from C:/Ruby27-x64/bin/jekyll:23:in `load'     
                                                                     
31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'     
                   
30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'   
                     
29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'  
                   
28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute' 
              
27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'  
               
26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute' 
                                                                                                                            
25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in 
init_with_program'        
                                                                                                 
24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'   
              
23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'    
              
22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'  
                                                                                                                           
21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:36:in `process' 
              
20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:65:in `build' 
                
19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/command.rb:28:in `process_site'
                 
18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/site.rb:68:in `process'    
                    
 17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/site.rb:105:in `reset'    
                      
16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/hooks.rb:102:in `trigger'  
                     
15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/hooks.rb:102:in `each'     
                     
14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-3.9.0/lib/jekyll/hooks.rb:103:in `block in trigger'     
         
13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme.rb:33:in `block in <top (required)>'                 
          
12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme.rb:27:in `init'    
                                                                                                                           
11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/munger.rb:25:in `munge!' 
                                                                             
10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/downloader.rb:24:in `run'  
                                                                                                                    
9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/downloader.rb:42:in `download'       
                                                                                                         
8: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:606:in `start'                                                         

7: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:933:in `start'                                                         

6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/downloader.rb:43:in `block in download'                                                                                                       

5: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:1492:in `request'                                                      

4: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:1536:in `transport_request'                                           

3: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http/response.rb:167:in `reading_body'                                         

2: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:1537:in `block in transport_request'                                   

1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/downloader.rb:44:in `block (2 levels) in download'                                                                                    

C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/downloader.rb:67:in `raise_unless_sucess': 404 - Not Found (Jekyll::RemoteTheme::DownloadError)
```  

## Environment
- Ruby version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32] 
- Jekyll version: jekyll 3.9.0
- Theme version: 4.0.0 but updated gemfile  to work with latest gh-pages https://github.com/olivia1117/LakeWaterLevelData/blob/gh-pages/Gemfile
- gh-pages 212
- running on Windows

**Comment by daviddarnes** [comment]
Hey @olivia1117, sounds like the same issue here https://github.com/daviddarnes/alembic/issues/167#issuecomment-762711292

You’ll need to state the branch by adding `@main` to the end of the remote theme value

**Comment by olivia1117** [comment]
Thank you for responding so quickly! Everything is fixed now!
